### ISSUE TITLE
Rendering problem

### ISSUE THREAD

**Issue by maurosoft1973** [akexorcist/Android-RoundCornerProgressBar#21]
Hi!
I have this error on preview layout:
java.lang.NullPointerException   at com.akexorcist.roundcornerprogressbar.RoundCornerProgressBar.setBackgroundLayoutSize(RoundCornerProgressBar.java:50)   at com.akexorcist.roundcornerprogressbar.common.BaseRoundCornerProgressBar.onMeasure(BaseRoundCornerProgressBar.java:220)

this is my layout file:
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/com.akexorcist.roundcornerprogressbar"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:background="#ff627e0f">

```
<LinearLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_gravity="center">
    <com.akexorcist.roundcornerprogressbar.RoundCornerProgressBar
        android:id="@+id/progress_splash_screen"
        android:layout_height="32dp"
        android:layout_width="match_parent"
        app:backgroundPadding="5dp" />
</LinearLayout>
```

</LinearLayout>

why??

**Comment by first087** [comment]
@akexorcist remove override setup mothod on RoundCornerProgressBar for fix it.

**Comment by maurosoft1973** [comment]
sorry, the setBackgroundLayoutSize is abstract method of BaseRoundCornerProgressBar e not possibile remove it

**Comment by maurosoft1973** [comment]
i use android studio versione 1.2.1.1, the problem is present on the sample project

**Comment by Spiderbezno** [comment]
I have the same error, in Android studio?

**Comment by JagDhruv** [comment]
facing the exact same issue.

**Comment by narutosanjiv** [comment]
Error StackTrace
java.lang.NullPointerException
    at com.akexorcist.roundcornerprogressbar.RoundCornerProgressBar.setBackgroundLayoutSize(RoundCornerProgressBar.java:48)
    at com.akexorcist.roundcornerprogressbar.BaseRoundCornerProgressBar.onMeasure(BaseRoundCornerProgressBar.java:218)
    at android.view.View.measure(View.java:17547)
    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
    at android.view.View.measure(View.java:17547)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
    at android.view.View.measure(View.java:17547)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
    at android.support.v7.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:453)
    at android.view.View.measure(View.java:17547)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
    at android.view.View.measure(View.java:17547)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:875)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
    at android.view.View.measure(View.java:17547)
    at com.android.layoutlib.bridge.impl.RenderSessionImpl.measureView(RenderSessionImpl.java:640)
    at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:540)
    at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:323)
    at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:350)
    at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:497)
    at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:485)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:894)
    at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:485)
    at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:590)
    at com.intellij.android.designer.designSurface.AndroidDesignerEditorPanel$6.run(AndroidDesignerEditorPanel.java:480)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
    at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
    at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

**Comment by akexorcist** [comment]
Already fixed on version 1.2.3
Please update and check this issue again

**Comment by Spiderbezno** [comment]
Error:(73, 13) Failed to resolve: com.akexorcist:RoundCornerProgressBar:1.2.3
<a href="openFile">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by akexorcist** [comment]
@Spiderbezno  It may still be pending on maven process (I just uploaded). Try again in a few hours.

**Comment by Spiderbezno** [comment]
OK

**Comment by atherkhan** [comment]
Hi, i have updated my code today with your latest one but still seeing this issue. StackTrace below

java.lang.NullPointerException
    at com.roundprogressbar.IconRoundCornerProgressBar.setBackgroundLayoutSize(IconRoundCornerProgressBar.java:105)
    at com.roundprogressbar.common.BaseRoundCornerProgressBar.onMeasure(BaseRoundCornerProgressBar.java:232)
    at android.view.View.measure(View.java:16497)
    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
    at android.view.View.measure(View.java:16497)
    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
    at android.view.View.measure(View.java:16497)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
    at android.view.View.measure(View.java:16497)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
    at android.view.View.measure(View.java:16497)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
    at android.view.View.measure(View.java:16497)

**Comment by akexorcist** [comment]
Preview layout should be work well on version 2.0.2. Please update and check it.
