### ISSUE TITLE
There is still error on older versions

### ISSUE THREAD

**Issue by sembozdemir** [akexorcist/Android-RoundCornerProgressBar#8]
Hi guys,

I am using your widget on my app. In android 2.3.7 version, I have an error although I use 1.1.0 version. It crashes while inflating the view. And there is logcat below:

```
882-882/com.sembozdemir.dortislem E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NoSuchMethodError: android.view.ViewTreeObserver.removeOnGlobalLayoutListener
            at com.akexorcist.roundcornerprogressbar.RoundCornerProgressBar$1.onGlobalLayout(RoundCornerProgressBar.java:109)
            at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:549)
            at android.view.ViewRoot.performTraversals(ViewRoot.java:1189)
            at android.view.ViewRoot.handleMessage(ViewRoot.java:1859)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3683)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
            at dalvik.system.NativeStart.main(Native Method)
```

by the way: [Click here](https://play.google.com/store/apps/details?id=com.sembozdemir.dortislem) if you want to see the app

**Comment by akexorcist** [comment]
Thanks! @first087  @kimbeejay

**Comment by atherkhan** [comment]
Hi, i think im having this same issue using the very latest code but im using Android 2.2.1 and i also tested on 2.3.3 emulator. Is this Android version too low ? Error log below.

FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test/com.test.MainPage}: android.view.InflateException: Binary XML file line #37: Error inflating class com.akexorcist.roundprogressbar.IconRoundCornerProgressBar
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2753)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2769)
at android.app.ActivityThread.access$2500(ActivityThread.java:129)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2117)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:143)
at android.app.ActivityThread.main(ActivityThread.java:4717)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #37: Error inflating class com.akexorcist.roundprogressbar.IconRoundCornerProgressBar
at android.view.LayoutInflater.createView(LayoutInflater.java:513)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:565)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:618)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:621)
at android.view.LayoutInflater.inflate(LayoutInflater.java:407)
at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:226)
at android.app.Activity.setContentView(Activity.java:1677)
at com.test.MainPage.onCreate(MainPage.java:100)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2717)
... 11 more
Caused by: java.lang.reflect.InvocationTargetException
at com.akexorcist.roundprogressbar.IconRoundCornerProgressBar.<init>(IconRoundCornerProgressBar.java:59)
at java.lang.reflect.Constructor.constructNative(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:446)
at android.view.LayoutInflater.createView(LayoutInflater.java:500)
... 22 more
Caused by: java.lang.NullPointerException
at com.akexorcist.roundprogressbar.common.BaseRoundCornerProgressBar.invalidateProgressLayout(BaseRoundCornerProgressBar.java:385)
at com.akexorcist.roundprogressbar.common.BaseRoundCornerProgressBar.invalidate(BaseRoundCornerProgressBar.java:381)
at android.view.View.setFlags(View.java:4559)
at android.view.ViewGroup.initViewGroup(ViewGroup.java:298)
at android.view.ViewGroup.<init>(ViewGroup.java:286)
at android.widget.LinearLayout.<init>(LinearLayout.java:115)
at com.akexorcist.roundprogressbar.common.BaseRoundCornerProgressBar.<init>(BaseRoundCornerProgressBar.java:67)
... 26 more

**Comment by akexorcist** [comment]
I update to 2.0.2 and set minimum requirement to 11.
